version: '3.8'

services:
  catalog-service:
    depends_on:
      - polar-postgres
    image: "catalog-service:latest"
    container_name: "catalog-service"
    ports:
      - 9001:9001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata

  order-service:
    depends_on:
      - polar-postgres
    image: "order-service:latest"
    container_name: "order-service"
    ports:
      - 9002:9002
    environment:
      - POLAR_CATALOG_SERVICE_URI=http://catalog-service:9001
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_R2DBC_URL=r2dbc:postgresql://polar-postgres:5432/polardb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://polar-postgres:5432/polardb_order

  config-server:
    image: "config-server:0.0.1-SNAPSHOT"
    container_name: "config-server"
    ports:
      - 8888:8888
    environment:
      - BPL_JVM_THREAD_COUNT=50

  polar-postgres:
    image: postgres:latest
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  polar-redis:
    image: redis:latest
    container_name: "polar-redis"
    ports:
      - 6379:6379